name: Run Tests with All ML Backends

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install critical dependencies explicitly first
        python -m pip install numpy pandas scikit-learn scipy
        # Install test dependencies
        python -m pip install pytest pytest-cov
        # Install the package in development mode
        python -m pip install -e ".[full]"
        # Verify numpy installation
        python -c "import numpy; print('NumPy version:', numpy.__version__)"

    - name: Test with pytest
      run: |
        python -m pytest -xvs tests/ --cov=pinard --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false