name: Run Tests with All ML Backends

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installer explicitement les dépendances critiques en premier
        python -m pip install numpy==1.24.3 pandas scikit-learn scipy PyWavelets
        # Vérifier que numpy est correctement installé
        python -c "import numpy; print('NumPy version:', numpy.__version__)"
        # Installer les dépendances de test
        python -m pip install pytest pytest-cov
        # Installer toutes les autres dépendances listées dans setup.py
        python -m pip install -e .
        # Installer les dépendances optionnelles (mais pas les frameworks ML lourds pour accélérer les tests)
        python -m pip install -e ".[test]"
        
    - name: List installed packages
      run: |
        pip list

    - name: Verify imports
      run: |
        # Vérifier que les imports essentiels fonctionnent
        python -c "import numpy; import pandas; import sklearn; import scipy; import pywt; print('All critical imports successful')"
        
    - name: Test with pytest
      run: |
        python -m pytest -xvs tests/ --cov=pinard --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false